site: anton's notes
url: https://antois.me/
title: anton's notes
description: Personal notes on data science and finance.
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""


markdown: kramdown
highlighter: rouge
   input: GFM

# highlighter: none

include:
  - _posts

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug # /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"